### ISSUE TITLE
个人观点

### ISSUE THREAD

**Issue by evanzlj** [JacksonTian/fks#132]
个人感觉，前端的根基在于交互，而这一点在对应的图纸上并没有标注，作为前端知识结构而言，底层支柱不应该写上么。。很多人在看这个东西以充实自己的大脑，但是应该将最基本的东西放上去，以免新入行的同学盲目追求技术的手段，而忽视了实现的目的

**Comment by wuxiaolan91** [comment]
具体来说，你是觉得应该多放点交互方面的书还是什么？能具体讲讲么？

**Comment by evanzlj** [comment]
我觉得这个技能汇总对我而言确实不错，可是对新入行的前端同学而言，应该对他们有个基本的前端进阶的思路，如果光看这个汇总，可能会拔苗助长，把前端发展看成一棵大树，根基是用户体验，主干是交互思想，而其他的手段都是大树的枝叶，然后再去推荐他们每个阶段要看什么，学什么，一步步走向熟手，专家。
 书是要放的，但是梳理新人的意识更关键。
公司现在很难招到合适的前端，面试的时候，问完框架问题，编程思想以后，再问他们交互设计，比如github在个人首页跳转到仓库页时的顶部蓝色条让他们做，会选择什么方式，怎么设计组件的结构，在什么时间(或者页面的哪个事件)出现这个蓝条。
![default](https://cloud.githubusercontent.com/assets/18155315/20784227/f05ee64c-b7d3-11e6-8a05-2e931331638d.png)
我知道这个项目叫技能汇总，既然有中文，希望它更好 ^ ^

**Comment by JacksonTian** [comment]
新手引导需要做的事情就更多了，这个项目不一定能承担这样的职责。这个项目最早创建是因为大家不知道有什么高大上的东西，所以我们帮助把最前沿的东西列举出来，让人了解到一张前端行业的大图。

当然，现在的人比较浮躁，比较喜欢花哨、时髦的东西，而忽略基础的知识，这种因人而异的情况，我们覆盖不了。

**Comment by hkongm** [comment]
是啊，面试者玩转react+flux的，我让他写几个css伪类，答写不上来，好久没写了。。。我就服了
