### ISSUE TITLE
可视化效果不『可视』

### ISSUE THREAD

**Issue by lexrus** [JacksonTian/fks#97]
http://html5ify.com/fks/chart/

中间的图太小了，几乎没法看，搞成全屏的会好很多。

**Comment by hjzheng** [comment]
完全看不清楚啊！ 推荐用D3.js 重做一下 
https://github.com/hjzheng/front-end-collect
你可以参考这个：get-set.cn/front-end-chart/

**Comment by JacksonTian** [comment]
已经采用楼上的新图

**Comment by lexrus** [comment]
好多了。
不过新的图在 Safari 8 下无法滚动，只能把光标移到图外面才行...
